### ISSUE TITLE
White noise when headphone plugged in

### ISSUE THREAD

**Issue by aluferraz** [chris1111/VoodooHDA-2.9.2-Clover-V13#7]
Hi there,

Whenever I plug in a headphone I get a constant white noise. Also, I need to plug in the headphone using the port Black Right, and not the P2 port.

HDMI audio comes clean.

Is there any way to solve this ?

Thanks !!

**Comment by chris1111** [comment]
Try this in Info.plist

<key>MixerValues</key>
    <dict>
	<key>PCM</key>
	<integer>90</integer>
	<key>Rec</key>
	<integer>90</integer>
	<key>iGain</key>
	<integer>0</integer>
	<key>iMix</key>
	<integer>30</integer>
    </dict>

**Comment by aluferraz** [comment]
Hi there,

Thanks a lot for replying ! I edited the file /System/Library/Extensions/VoodooHDA.kext/Contents/Info.plist with your values, but nothing changed.

The weird thing is that on the PrefsPane the values are not changed.

Attached some screenshots and my Info.plist
[Archive.zip](https://github.com/chris1111/VoodooHDA-2.9.2-Clover-V13/files/3247861/Archive.zip)

**Comment by chris1111** [comment]
> Hi there,
> 
> Thanks a lot for replying ! I edited the file /System/Library/Extensions/VoodooHDA.kext/Contents/Info.plist with your values, but nothing changed.
> 
> The weird thing is that on the PrefsPane the values are not changed.
> 
> Attached some screenshots and my Info.plist
> [Archive.zip](https://github.com/chris1111/VoodooHDA-2.9.2-Clover-V13/files/3247861/Archive.zip)

If you edit kext, you need to editing the kext in Desktop and reinstall  the kext with the correct permission

**Comment by aluferraz** [comment]
![image](https://user-images.githubusercontent.com/5156410/58815529-26c2d180-85fe-11e9-8447-b62721ac3064.png)
Now the values have changed, but the white noise still there.

**Comment by chris1111** [comment]
> ![image](https://user-images.githubusercontent.com/5156410/58815529-26c2d180-85fe-11e9-8447-b62721ac3064.png)
> Now the values have changed, but the white noise still there.

Take look here to find a solution ??
https://olarila.com/forum/viewtopic.php?t=454
